apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: testnewose-mar6
  janus-idp.io/tekton: testnewose-mar6
  backstage.io/kubernetes-id: testnewose-mar6
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: testnewose-mar6
resources:
  - application-dev.yaml
