apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-testnewose-mar6-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-testnewose-mar6-gitops
    spec:
      serviceAccountName: testnewose-mar6-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=testnewose-mar6-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/testnewose-mar6-notebook -- git clone https://github.com/jdubrick-ai/testnewose-mar6
      restartPolicy: Never
