apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: testnewose-mar6
  janus-idp.io/tekton: testnewose-mar6
  backstage.io/kubernetes-id: testnewose-mar6
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: testnewose-mar6
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
