apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: testnewose-mar6
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/testnewose-mar6:7e9211b2c344942204755fe2dc6d4e3140e3a87c@sha256:1e419ee4960a5147e0296fc25cde1af29c70c6eb7a2d803c588e06453b38830e # use pre-built to bootstrap
          name: app-inference
